[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "AIinNCEE: An Introduction to some boring gamesmanship used in the National College Entrance Examination of the the People's Republic of China"

[preprocessor.tera]

[output.latex]
latex    = true
pdf      = false
markdown = true
