[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "AIinNCEE: An Introduction to essentials used in the National College Entrance Examination of the the People's Republic of China, A Great Involution"

[build]
create-missing = false

[output.html]
mathjax-support = true

#[output.latex]
#latex    = true
#pdf      = false
#markdown = true

#[output.linkcheck]
#follow-web-links = true

#[output.html.fold]
#enable = true
#level = 0
